### PR TITLE
Fixes web interface

### LINKED ISSUE #136: Web interface needs an update
Google maps seems to have changed some things with its api. When I load the page, I am greeted with a popup saying : "this page can't load google maps correctly". After dismissing the alert, the map shown is really dark and has a bunch of "for development only" watermarks.

### PR DESCRIPTION
**Pull request by cedarmora**
Fixes #136 web interface error and updates the mapping interface and README to reflect changes in the google maps API.

### CODE REVIEW

**Comment by PHPoenX** [comment]
It dont works

**Comment by cedarmora** [comment]
PHPoenx, did you follow the instructions I added to the readme?

**Comment by ereyes01** [comment]
This worked for me, and the change is pretty simple. It would be nice if the API key could be passed in via a CLI arg, or an environment variable. But it worked for me as-is after following the instructions.

**Comment by cedarmora** [comment]
For sure, CLI or something would be better but I didn’t have the time to
figure it out.

**Comment by dh47** [comment]
Any way to switch to OpenStreetMap?

**Comment by antirez** [comment]
Would using open street map fix the issue? Or it would still require an API key? If OSM does not require any API key I could switch to their APIs.

**Comment by cedarmora** [comment]
It looks like neither of the OSM tile providers require an API key: 

https://switch2osm.org/using-tiles/getting-started-with-leaflet/

https://switch2osm.org/using-tiles/getting-started-with-openlayers/

**Comment by antirez** [comment]
I tested it a few seconds, I think I really want to switch dump1090 to OSM. I'll do some work in the next days to see if it has all the features we need.

**Comment by antirez** [comment]
Ported to OSM. Closing.

**Pull request closed without merging**
